const THEME_PRESETS = {
  "vscode-dark": {
    background: "#1e1e1e",
    foreground: "#d4d4d4",
    cursor: "#d4d4d4",
    selectionBackground: "#264f78",
    black: "#000000",
    red: "#cd3131",
    green: "#0dbc79",
    yellow: "#e5e510",
    blue: "#2472c8",
    magenta: "#bc3fbc",
    cyan: "#11a8cd",
    white: "#e5e5e5",
    brightBlack: "#666666",
    brightRed: "#f14c4c",
    brightGreen: "#23d18b",
    brightYellow: "#f5f543",
    brightBlue: "#3b8eea",
    brightMagenta: "#d670d6",
    brightCyan: "#29b8db",
    brightWhite: "#ffffff"
  },
  "ghostty-ink": {
    background: "#0f1728",
    foreground: "#dbe5ff",
    cursor: "#dbe5ff",
    selectionBackground: "#2f446f",
    black: "#1b2232",
    red: "#f28fad",
    green: "#abe9b3",
    yellow: "#fae3b0",
    blue: "#96cdfb",
    magenta: "#ddb6f2",
    cyan: "#89dceb",
    white: "#d9e0ee",
    brightBlack: "#4f5a72",
    brightRed: "#f8a5c2",
    brightGreen: "#b9f4c2",
    brightYellow: "#fce6bd",
    brightBlue: "#a4d8ff",
    brightMagenta: "#e6c2f9",
    brightCyan: "#94e2f0",
    brightWhite: "#ffffff"
  },
  "midnight-blue": {
    background: "#050d2a",
    foreground: "#00e5ff",
    cursor: "#8bf3ff",
    selectionBackground: "#1c3f8f",
    black: "#001034",
    red: "#ff5f87",
    green: "#5fffaf",
    yellow: "#ffd15f",
    blue: "#5f8fff",
    magenta: "#af7dff",
    cyan: "#4ee6ff",
    white: "#ccf9ff",
    brightBlack: "#2d4a8f",
    brightRed: "#ff88ab",
    brightGreen: "#86ffbf",
    brightYellow: "#ffe08c",
    brightBlue: "#84a8ff",
    brightMagenta: "#ca9fff",
    brightCyan: "#80f0ff",
    brightWhite: "#f4ffff"
  }
};

module.exports = { THEME_PRESETS };
